// flow-typed signature: a838d66594d5a18dfbfa4f946647f391
// flow-typed version: <<STUB>>/eslint-index_v^1.2.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-index'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-index' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-index/bin/cli' {
  declare module.exports: any;
}

declare module 'eslint-index/bin/constants' {
  declare module.exports: any;
}

declare module 'eslint-index/bin/docs' {
  declare module.exports: any;
}

declare module 'eslint-index/bin/formatter' {
  declare module.exports: any;
}

declare module 'eslint-index/bin/index' {
  declare module.exports: any;
}

declare module 'eslint-index/bin/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-index/bin/cli.js' {
  declare module.exports: $Exports<'eslint-index/bin/cli'>;
}
declare module 'eslint-index/bin/constants.js' {
  declare module.exports: $Exports<'eslint-index/bin/constants'>;
}
declare module 'eslint-index/bin/docs.js' {
  declare module.exports: $Exports<'eslint-index/bin/docs'>;
}
declare module 'eslint-index/bin/formatter.js' {
  declare module.exports: $Exports<'eslint-index/bin/formatter'>;
}
declare module 'eslint-index/bin/index.js' {
  declare module.exports: $Exports<'eslint-index/bin/index'>;
}
declare module 'eslint-index/bin/parser.js' {
  declare module.exports: $Exports<'eslint-index/bin/parser'>;
}
