// flow-typed signature: 5e5551e49c2c4c47921172c5377d4ec2
// flow-typed version: <<STUB>>/@rdbird/eslint-config_v^5.6.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rdbird/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rdbird/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rdbird/eslint-config/__tests__/fixtures/block' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/__tests__/fixtures/flowtype' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/__tests__/fixtures/jsdoc' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/__tests__/fixtures/react_component' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/all' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/base' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/flowtype' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/jsx-a11y' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/react' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/rules/ecma/index' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/rules/flowtype/index' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/rules/jsdoc/index' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/rules/jsx-a11y/index' {
  declare module.exports: any;
}

declare module '@rdbird/eslint-config/rules/react/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rdbird/eslint-config/__tests__/fixtures/block.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/__tests__/fixtures/block'>;
}
declare module '@rdbird/eslint-config/__tests__/fixtures/flowtype.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/__tests__/fixtures/flowtype'>;
}
declare module '@rdbird/eslint-config/__tests__/fixtures/jsdoc.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/__tests__/fixtures/jsdoc'>;
}
declare module '@rdbird/eslint-config/__tests__/fixtures/react_component.jsx' {
  declare module.exports: $Exports<'@rdbird/eslint-config/__tests__/fixtures/react_component'>;
}
declare module '@rdbird/eslint-config/all.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/all'>;
}
declare module '@rdbird/eslint-config/base.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/base'>;
}
declare module '@rdbird/eslint-config/flowtype.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/flowtype'>;
}
declare module '@rdbird/eslint-config/index' {
  declare module.exports: $Exports<'@rdbird/eslint-config'>;
}
declare module '@rdbird/eslint-config/index.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config'>;
}
declare module '@rdbird/eslint-config/jsx-a11y.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/jsx-a11y'>;
}
declare module '@rdbird/eslint-config/react.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/react'>;
}
declare module '@rdbird/eslint-config/rules/ecma/index.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/rules/ecma/index'>;
}
declare module '@rdbird/eslint-config/rules/flowtype/index.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/rules/flowtype/index'>;
}
declare module '@rdbird/eslint-config/rules/jsdoc/index.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/rules/jsdoc/index'>;
}
declare module '@rdbird/eslint-config/rules/jsx-a11y/index.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/rules/jsx-a11y/index'>;
}
declare module '@rdbird/eslint-config/rules/react/index.js' {
  declare module.exports: $Exports<'@rdbird/eslint-config/rules/react/index'>;
}
